language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: griff_rees
  password:
    secure: dCdliHQIsQOqHPoZurtE/wxYAoOPwt+UNaJKZ6CJcYRcj1LyX6k6RbqTvVxepEpTY1y15Wy8BRtv2feXf+ePNm1sq5ZmtZZp7TKo2KHuQaE8EL0EyBkpCI+hcQBYBgm6fhdIFdMjHxfWn0o04c6tVymRMjMHQrucHv33mm72utImqnErE8prsrXc5Nj7OlyKAZ5KvLy9nPByyGKKrhlX6uL22fiqRRKeBF/+16CosjWJ+tzexhQPy+quZdo7+ZzYnWJIv2OvDg9G1ch398OYRUihQGpjkCKnRHlUZPPs9QRKupK1PWm6sqaaYrho+9ccpvsrnwQRIp1I+UrbwQ6OA0D0sjJKk6gq3sNBL8yIGCzfNg5GNtxXV+qM7QjnuKeZj0/gWDdMfWceBUDzkZIyQSBEeoeyIL7bcaYnTDUFjrZMcbRMtIwgqXwycek/6Jl15Gq3qni+HOvC/FPWtwGAGUZNXmE8ebGRO/aLbxwaaYh+nvYi30SLvpq5nq1FPG83xC50EueMBfQPaYFnJtoep8pvsjKEHrthpvInIwlwuK9apLsTkA/Cw0pnpQmkPw/YRwAIf2T+IHiF2+FF1lOXLBl7y2610TkDpfPisbfE/jQOww7LfRjBa0uBdBkn6Wg/ExRIJk0r3/wM+1uXbcdQ9tEBZI5+xQ5CfVNBr9YfUAY=
  on:
    tags: true
    repo: spool/uk_boards
    python: 3.8
