language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: griff_rees
  password:
    secure: wzldHLsF32DJ9T3fxPR0P8pvI+hp/h8gACyGvh8LPOWRO70pv6Ttu+gmBu744NuQzfEZbZklmjDfWVzXb7Cl7nVm7jO0FRbk/spqpOPs7xSIo+mYFR2hTYf27u+MoP1IIzcvdqRBHsFUBUGyzXEd+9kJZ2HNs6Ss7H1Bu79sbwzCU+d0uOZO8Os+2uGkUfT3m81zdlfVBuG1gwP7E5AhjkktMN1MhUZPkeAUw3NHUNwp48h+GHpd8bcEGm0s3QXxU3awizQNO11HeEmk4UtqiF161CiEAmiyElXzV9DHiJnoNh4BUtq+0n+wPGOQxGSUI1BfXtTZdXQm3KutRtEiywCERTU9Ynio6VafoR1MV1YgL+GGheuzOT8qGgExBf1htP5GzUig0BRKOWaKexgu+bGro+AIYStHCfD85ol8o5AxtcOAnb8w1adI1i06w7fkWBBETUXo49mLbXWh/eG4svvIsT5/oy10h3gUv3QQGcf/lJzMrXkPJhg477hQTV8ZP+FMZfXUYD7oE7UB1DydZvzh6Rf/6jXwYK0TbQRNrdOItuv1dOM05XfpyuioRKovqoFRPLd/XzJoEbnlYcnue7mx//1SoRpvrRznowk9IawHrB5/hBqkil0HRKEmkM9r8DoLLvMhHOmD6/yzQLERs4NvyOzq0O2gR9jboQFvgCo=
  on:
    tags: true
    repo: spool/uk_boards
    python: 3.8
